CREATE DATABASE ASSIGNMENT_1
USE ASSIGNMENT_1
SET SQL_SAFE_UPDATES = 0;
CREATE TABLE WORKER_1(
ID INT,
FIRST_NAME VARCHAR(25),
DEPARTMENT VARCHAR(25),
LOCATION VARCHAR(25),
SALARY INT
);
SELECT * FROM WORKER_1
INSERT INTO WORKER_1 VALUES(1,'AMITABH','DATA','LDH',45000);
INSERT INTO WORKER_1 VALUES(2,'MORISH','SALES','POP',45000);
INSERT INTO WORKER_1 VALUES(3,'RISHAV','DATA','KUC',47000);
INSERT INTO WORKER_1 VALUES(4,'VIPUL','SALES','DLI',48000);
INSERT INTO WORKER_1 VALUES(5,'SATISH','SALES','NDLS',49000);
INSERT INTO WORKER_1 VALUES(6,'ABHI','CONST','JUC',50000);
INSERT INTO WORKER_1 VALUES(7,'VIKAS','CONST','LUCK',51000);
SELECT * FROM WORKER_1


#Q.1Write an SQL query to print the first three characters of  FIRST_NAME from Worker
table.

SELECT * FROM WORKER_1
SELECT SUBSTRING(FIRST_NAME ,1,3) AS EXTRACT_STRING FROM WORKER_1

#Q2Write an SQL query to find the position of the alphabet (‘a’) in the first name
column ‘Amitabh’ from Worker table.

SELECT POSITION('a' IN FIRST_NAME)FROM WORKER_1;

#Q3Write an SQL query to print the name of employees having the highest salary in each DEPARTMENT 


SELECT*FROM WORKER_1

SELECT FIRST_NAME,DEPARTMENT, MAX(SALARY) FROM WORKER_1 GROUP BY DEPARTMENT;





